CREATE DATABASE IF NOT EXISTS empresas_db
  DEFAULT CHARACTER SET = utf8mb4;
USE empresas_db;

CREATE TABLE empresas (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(80) NOT NULL,
  cnpj CHAR(14) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  role ENUM('EMPRESA','ADMIN') NOT NULL DEFAULT 'EMPRESA',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ux_empresas_cnpj (cnpj),
  UNIQUE KEY ux_empresas_usuario (usuario),
  CHECK (cnpj REGEXP '^[0-9]{14}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
